version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./webshop:/app
        
    php:
        image: php:fpm
        volumes:
            - ./webshop:/app
            - ./:/install
