version: '3'
services:
    web:
        image: nginx:latest
        #ports:
        #    - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./webshop:/app
        networks:
            - traefik_web
            - internal
        labels:
            - traefik.http.routers.php.rule=Host(`hb.dev.somogyi.xyz`)
            - traefik.http.routers.php.tls=true
            - traefik.http.routers.php.tls.certresolver=lets-encrypt
            - traefik.port=80
            - "traefik.http.routers.php.entrypoints=websecure,websecure_internal"
            - "traefik.http.routers.php.tls.certresolver=letsencryptresolver"
            - traefik.http.services.php.loadbalancer.server.port=80
    php:
        image: php:fpm
        volumes:
            - ./webshop:/app
        networks:
            - internal
        labels:
            - traefik.enable=false

networks:
    traefik_web:
        external: true
    internal:
        external: false
